# Override these settings with your own
languageCode = "en-us"
baseURL = "https://jakob.schwalb-willmann.de/"
copyright = "© {year} Jakob Schwalb-Willmann"
title = "Jakob Schwalb-Willmann"

# The value "hugo-theme-codex" is only to get the exampleSite
# to work in this repo. Change to whatever name you gave the theme
# when you added it. If you followed the README, you should have 
# added the theme using the name "codex".
theme = "hugo-theme-codex"

# REMOVE THIS!
# This is only to get the exampleSite to work in this repo.

# Add your Disqus shortname here.
# disqusShortname = ""

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = "" 

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "January 2, 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/schwalbwillmann"
  github = "https://github.com/16eagle"
  email = "mailto:jakob.schwalb-willmann@uni-wuerzburg.de"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  # instagram = "https://instagram.com/<your handle>"
  # linkedin = "<link to your profile>"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconTitles = ["Twitter", "GitHub"]
  ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"
  weight = 1


[[menu.main]]
  identifier = "projects"
  name = "projects"
  title = "projects"
  url = "/projects"
  weight = 1

[[menu.main]]
  identifier = "publications"
  name = "publications"
  title = "publications"
  url = "/publications"
  weight = 3

[[menu.main]]
  identifier = "talks"
  name = "talks"
  title = "talks"
  url = "/talks"
  weight = 2

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"
  weight = 4

